import Head from 'next/head';
import React from 'react';
import Image from 'next/image';
import { Navbar } from '../../../components/Navbar/Navbar';
import { classesConfig } from '../../../constants/classes';
import { Badge } from '../../../components/Badge/Badge';
import { useRouter } from 'next/router';
import { Tooltip } from '@nextui-org/react';
import { ArmorPopover } from '../../../components/ArmorPopover/ArmorPopover';
import { WeaponPopover } from '../../../components/WeaponPopover/WeaponPopover';
import { builds } from '../../../builds/builds';
import { Build } from '../../../constants/terrariaBuilds';

export async function getStaticProps(staticProps: Build) {
  const params = staticProps.params
  const buildData = builds.filter((build => build.id === id))
  return {
    props: {
      builds: buildsData,
    }
  }
}

export async function getStaticPaths() {
  const id
  const buildData = builds.filter((build => build.id === id))
  return {
    paths: [params: buildsData[0].id],
    fallback: false, // can also be true or 'blocking'
  }
}

const BuildPage = () => {

  const router = useRouter();

  return (
    <div className='flex flex-col h-screen overflow-y-auto'>
      <Head>
        <title>Terraria Builds | Ninja zabijak</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <div className='flex flex-col mt-16 mx-40 space-y-3 mb-10 h-full'>
        <div className="flex space-x-2">
          <div className='grayContainer items-center flex w-20 p-3'>
            <Tooltip content={classesConfig[0].name}>
              <Image
                priority={true}
                src={classesConfig[0].src}
                alt={classesConfig[0].name}
                width='50px'
                height='50px'
              />
            </Tooltip>
          </div>
          <div className='flex grayContainer flex-col items-start w-full p-3'>
            <h1>BUILD_NAME</h1>
            <Badge badge="Vanilla" />
          </div>
        </div>
        <div className=" h-full flex flex-col grayContainer p-8 space-y-10">
          <div className='flex space-x-16'>
            <div className='flex flex-col w-64 space-y-4 text-center'>
              <ArmorPopover />
              <span className='font-semibold wordBreak'>ARMOR_NAME</span>
            </div>
            <div className='grid grid-cols-2 grid-rows-2 gap-x-10 items-center h-64'>
              <WeaponPopover />
              <WeaponPopover />
              <WeaponPopover />
              <WeaponPopover />
            </div>
          </div>
          <div className='flex flex-col'>
            <h1>DESCRIPTION</h1>
          </div>
        </div>
      </div>
    </div>
  )
};

export default BuildPage;
