import Head from 'next/head';
import React from 'react';
import Image from 'next/image';
import { Navbar } from '../../../components/Navbar/Navbar';
import { classesConfig } from '../../../constants/classes';
import { Badge } from '../../../components/Badge/Badge';
import { Tooltip } from '@nextui-org/react';
import { ArmorPopover } from '../../../components/ArmorPopover/ArmorPopover';
import { WeaponPopover } from '../../../components/WeaponPopover/WeaponPopover';
import { NextPage } from 'next';
import { useRouter } from 'next/router';
import { getBuildById } from '../../api/getBuildById';

const BuildPage: NextPage = () => {
  const router = useRouter();
  const { buildId } = router.query;

  const build = getBuildById(buildId, 2);

  return (
    <div className='flex flex-col h-screen overflow-y-auto'>
      <Head>
        <title>Terraria Builds | kkt</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <div className='flex flex-col mt-16 mx-40 space-y-3 mb-10 h-full'>
        <div className='flex space-x-2'>
          <div className='grayContainer items-center flex w-20 p-3'>
            <Tooltip content={classesConfig[0].name}>
              <Image
                priority={true}
                src={classesConfig[0].src}
                alt={classesConfig[0].name}
                width='50px'
                height='50px'
              />
            </Tooltip>
          </div>
          <div className='flex grayContainer flex-col items-start w-full p-3'>
            <h1>kkt</h1>
            <Badge badge='Vanilla' />
          </div>
        </div>
        <div className=' h-full flex flex-col grayContainer p-8 space-y-10'>
          <div className='flex space-x-16'>
            <div className='flex flex-col w-64 space-y-4 text-center'>
              <ArmorPopover />
              <span className='font-semibold wordBreak'>ARMOR_NAME</span>
            </div>
            <div className='grid grid-cols-2 grid-rows-2 gap-x-10 items-center h-64'>
              <WeaponPopover />
              <WeaponPopover />
              <WeaponPopover />
              <WeaponPopover />
            </div>
          </div>
          <div className='flex flex-col'>
            <h1>DESCRIPTION</h1>
          </div>
        </div>
      </div>
    </div>
  );
};

export default BuildPage;
