import { accessories } from '../constants/accessories';
import { armors } from '../constants/armors';
import { classesConfig } from '../constants/classes';
import { weapons } from '../constants/weapons';

export const builds = [
  {
    id: 1,
    name: 'Ninja zabijak',
    armor: armors.reaverArmor,
    classType: classesConfig[0],
    weapons: [weapons.Galaxia, weapons.Galaxia],
    accessories: [
      accessories.warbannerOfTheSun,
      accessories.warbannerOfTheSun,
      accessories.warbannerOfTheSun,
    ],
    badge: 'Calamity',
    borderColor: 'border-preCalamitas',
  },
  {
    id: 2,
    name: 'Choj do pice',
    armor: armors.reaverArmor,
    classType: classesConfig[1],
    weapons: [weapons.Galaxia, weapons.Galaxia, weapons.Galaxia],
    accessories: [accessories.warbannerOfTheSun],
    badge: 'Vanilla',
    borderColor: 'border-preCalamitas',
  },
  {
    id: 3,
    name: 'Ninja zabijak',
    armor: armors.reaverArmor,
    classType: classesConfig[2],
    weapons: [weapons.Galaxia, weapons.Galaxia],
    accessories: [
      accessories.warbannerOfTheSun,
      accessories.warbannerOfTheSun,
      accessories.warbannerOfTheSun,
    ],
    badge: 'Calamity',
    borderColor: 'border-preCalamitas',
  },
  {
    id: 4,
    name: 'Ninja zabijak',
    armor: armors.reaverArmor,
    classType: classesConfig[3],
    weapons: [weapons.Galaxia, weapons.Galaxia],
    accessories: [
      accessories.warbannerOfTheSun,
      accessories.warbannerOfTheSun,
      accessories.warbannerOfTheSun,
    ],
    badge: 'Calamity',
    borderColor: 'border-preCalamitas',
  },
  {
    id: 5,
    name: 'Ninja zabijak',
    armor: armors.reaverArmor,
    classType: classesConfig[4],
    weapons: [weapons.Galaxia, weapons.Galaxia],
    accessories: [
      accessories.warbannerOfTheSun,
      accessories.warbannerOfTheSun,
      accessories.warbannerOfTheSun,
    ],
    badge: 'Vanilla',
    borderColor: 'border-preCalamitas',
  },
  {
    id: 6,
    name: 'Ninja zabijak',
    armor: armors.reaverArmor,
    classType: classesConfig[3],
    weapons: [weapons.Galaxia, weapons.Galaxia],
    accessories: [
      accessories.warbannerOfTheSun,
      accessories.warbannerOfTheSun,
      accessories.warbannerOfTheSun,
    ],
    badge: 'Vanilla',
    borderColor: 'border-preCalamitas',
  },
  {
    id: 1,
    name: 'Ninja zabijak',
    armor: armors.reaverArmor,
    classType: classesConfig[0],
    weapons: [weapons.Galaxia, weapons.Galaxia],
    accessories: [
      accessories.warbannerOfTheSun,
      accessories.warbannerOfTheSun,
      accessories.warbannerOfTheSun,
    ],
    badge: 'Calamity',
    borderColor: 'border-preCalamitas',
  },
  {
    id: 1,
    name: 'Ninja zabijak',
    armor: armors.reaverArmor,
    classType: classesConfig[0],
    weapons: [weapons.Galaxia, weapons.Galaxia],
    accessories: [
      accessories.warbannerOfTheSun,
      accessories.warbannerOfTheSun,
      accessories.warbannerOfTheSun,
    ],
    badge: 'Calamity',
    borderColor: 'border-preCalamitas',
  },
  {
    id: 1,
    name: 'Ninja zabijak',
    armor: armors.reaverArmor,
    classType: classesConfig[0],
    weapons: [weapons.Galaxia, weapons.Galaxia],
    accessories: [
      accessories.warbannerOfTheSun,
      accessories.warbannerOfTheSun,
      accessories.warbannerOfTheSun,
    ],
    badge: 'Calamity',
    borderColor: 'border-preCalamitas',
  },
  {
    id: 1,
    name: 'Ninja zabijak',
    armor: armors.reaverArmor,
    classType: classesConfig[0],
    weapons: [weapons.Galaxia, weapons.Galaxia],
    accessories: [
      accessories.warbannerOfTheSun,
      accessories.warbannerOfTheSun,
      accessories.warbannerOfTheSun,
    ],
    badge: 'Calamity',
    borderColor: 'border-preCalamitas',
  },
  {
    id: 1,
    name: 'Ninja zabijak',
    armor: armors.reaverArmor,
    classType: classesConfig[0],
    weapons: [weapons.Galaxia, weapons.Galaxia],
    accessories: [
      accessories.warbannerOfTheSun,
      accessories.warbannerOfTheSun,
      accessories.warbannerOfTheSun,
    ],
    badge: 'Calamity',
    borderColor: 'border-preCalamitas',
  },
  {
    id: 1,
    name: 'Ninja zabijak',
    armor: armors.reaverArmor,
    classType: classesConfig[0],
    weapons: [weapons.Galaxia, weapons.Galaxia],
    accessories: [
      accessories.warbannerOfTheSun,
      accessories.warbannerOfTheSun,
      accessories.warbannerOfTheSun,
    ],
    badge: 'Calamity',
    borderColor: 'border-preCalamitas',
  },
];
